[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
aoc-runner = "*"
aoc-runner-derive = "*"

[dev-dependencies]
proptest = "1"
proptest-derive = "0.5.0"
tempfile = "3.14"
