[package]
name = "parse_ints"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true

[dev-dependencies]
proptest.workspace = true
proptest-derive.workspace = true
tempfile.workspace = true
