version = 1

[install]
# Rust toolchain
cargo = { pkg-path = "cargo", pkg-group = "rust-toolchain" }
rustc = { pkg-path = "rustc", pkg-group = "rust-toolchain" }
clippy = { pkg-path = "clippy", pkg-group = "rust-toolchain" }
rustfmt = { pkg-path = "rustfmt", pkg-group = "rust-toolchain" }
rust-lib-src = { pkg-path = "rustPlatform.rustLibSrc", pkg-group = "rust-toolchain" }

# rust-analyzer goes in its own group because it's updated
# on a different cadence from the compiler and doesn't need
# to match versions
rust-analyzer = { pkg-path = "rust-analyzer", pkg-group = "rust-analyzer" }

# Linkers
gcc = { pkg-path = "gcc" }

# Platform-specific libraries

# Extra tools
cargo-nextest.pkg-path = "cargo-nextest"
valgrind.pkg-path = "valgrind"
hyperfine.pkg-path = "hyperfine"
cargo-criterion.pkg-path = "cargo-criterion"

[vars]
# Allows me to use nightly features without a nightly compiler
RUSTC_BOOTSTRAP = "1"

[hook]

[profile]

[options]
systems = ["x86_64-linux"]
