[package]
name = "day1_naive"
version = "0.1.0"
edition = "2021"

[lib]
name = "day1_naive"
path = "src/lib.rs"

[[bin]]
name = "day1_naive"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "benchmark"
harness = false
